export type Category = "grill" | "sets" | "starters" | "ramen" | "drinks";

export type MenuItem = {
  id: string;
  name: string;
  jp: string;
  desc: string;
  price: number;
  category: Category;
  img: string;
  popular?: boolean;
  veg?: boolean;
};

export const CATEGORY_LABELS: Record<Category, string> = {
  grill: "Skewers",
  sets: "Set Menus",
  starters: "Starters",
  ramen: "Salads & Ramen",
  drinks: "Drinks",
};

export const MENU: MenuItem[] = [
  // ── Grillspieße (Skewers) ─────────────────────────────────
  {
    id: "yakitori",
    name: "Yakitori",
    jp: "焼き鳥",
    desc: "Chicken thigh skewer, tare glaze.",
    price: 4.5,
    category: "grill",
    img: "/images/tori.jpg",
    popular: true,
  },
  {
    id: "tebasaki",
    name: "Tebasaki",
    jp: "手羽先",
    desc: "Chicken wing skewer, salt & pepper.",
    price: 4.5,
    category: "grill",
    img: "/images/kawa.jpg",
  },
  {
    id: "meatballs",
    name: "Hühnerfleischbällchen",
    jp: "つくね",
    desc: "Hand-formed chicken meatballs, tare glaze.",
    price: 4.5,
    category: "grill",
    img: "/images/tsukune.jpg",
    popular: true,
  },
  {
    id: "chicken-hawaii",
    name: "Chicken Hawaii",
    jp: "チキンハワイ",
    desc: "Chicken with grilled pineapple, teriyaki glaze.",
    price: 4.9,
    category: "grill",
    img: "/images/hero.jpg",
  },
  {
    id: "pork",
    name: "Schweinefleisch",
    jp: "豚肉",
    desc: "Pork skewer, sweet soy glaze.",
    price: 4.5,
    category: "grill",
    img: "/images/buta.jpg",
  },
  {
    id: "pork-leek",
    name: "Schweinefleisch mit Lauchzwiebel",
    jp: "豚ねぎ",
    desc: "Pork with spring onion.",
    price: 5.5,
    category: "grill",
    img: "/images/negima.jpg",
  },
  {
    id: "pork-tomato",
    name: "Schweinefleisch mit Kirschtomaten",
    jp: "豚トマト",
    desc: "Pork with cherry tomatoes.",
    price: 5.5,
    category: "grill",
    img: "/images/veg.jpg",
  },
  {
    id: "beef-filet",
    name: "Rinderfilet",
    jp: "牛肉",
    desc: "Beef fillet skewer, grilled over binchotan.",
    price: 6.5,
    category: "grill",
    img: "/images/beef.jpg",
    popular: true,
  },
  {
    id: "beef-cheese",
    name: "Rindfleisch mit Käsefüllung",
    jp: "牛チーズ",
    desc: "Beef skewer with cheese filling.",
    price: 5.5,
    category: "grill",
    img: "/images/beef.jpg",
  },
  {
    id: "beef-mushroom",
    name: "Rindfleisch mit Nadelpilzen",
    jp: "牛きのこ",
    desc: "Beef skewer with needle mushrooms.",
    price: 6.5,
    category: "grill",
    img: "/images/beef.jpg",
  },
  {
    id: "lamb",
    name: "Lammfleisch",
    jp: "子羊",
    desc: "Lamb skewer.",
    price: 5.9,
    category: "grill",
    img: "/images/beef.jpg",
  },
  {
    id: "duck",
    name: "Entenbrust",
    jp: "鴨",
    desc: "Duck breast skewer.",
    price: 5.9,
    category: "grill",
    img: "/images/beef.jpg",
  },
  {
    id: "rotbarsch",
    name: "Rotbarsch",
    jp: "赤魚",
    desc: "Redfish skewer.",
    price: 4.9,
    category: "grill",
    img: "/images/fish.jpg",
  },
  {
    id: "lachs",
    name: "Lachs",
    jp: "鮭",
    desc: "Salmon skewer.",
    price: 5.5,
    category: "grill",
    img: "/images/fish.jpg",
  },
  {
    id: "tintenfisch",
    name: "Tintenfisch",
    jp: "烏賊",
    desc: "Squid skewer.",
    price: 5.9,
    category: "grill",
    img: "/images/fish.jpg",
  },
  {
    id: "garnelen",
    name: "Großgarnelen",
    jp: "海老",
    desc: "King prawn skewer.",
    price: 5.5,
    category: "grill",
    img: "/images/ebi.jpg",
    popular: true,
  },
  {
    id: "unagi",
    name: "Unagi",
    jp: "うなぎ",
    desc: "Grilled eel, tare glaze.",
    price: 6.9,
    category: "grill",
    img: "/images/fish.jpg",
  },
  {
    id: "zucchini",
    name: "Zucchini",
    jp: "ズッキーニ",
    desc: "Grilled zucchini skewer.",
    price: 2.5,
    category: "grill",
    img: "/images/veg.jpg",
    veg: true,
  },
  {
    id: "wasserkastanien",
    name: "Wasserkastanien",
    jp: "菱の実",
    desc: "Grilled water chestnut skewer.",
    price: 3.5,
    category: "grill",
    img: "/images/veg.jpg",
    veg: true,
  },
  {
    id: "kirschtomaten",
    name: "Kirschtomaten",
    jp: "トマト",
    desc: "Grilled cherry tomato skewer.",
    price: 3.0,
    category: "grill",
    img: "/images/veg.jpg",
    veg: true,
  },
  {
    id: "shiitake",
    name: "Shiitake Pilze",
    jp: "椎茸",
    desc: "Grilled shiitake mushrooms, tare glaze.",
    price: 3.9,
    category: "grill",
    img: "/images/mushroom.jpg",
    veg: true,
  },
  {
    id: "okra",
    name: "Okra",
    jp: "オクラ",
    desc: "Grilled okra skewer.",
    price: 3.5,
    category: "grill",
    img: "/images/veg.jpg",
    veg: true,
  },
  {
    id: "tofu",
    name: "Tofu",
    jp: "豆腐",
    desc: "Grilled tofu skewer.",
    price: 3.0,
    category: "grill",
    img: "/images/veg.jpg",
    veg: true,
  },
  {
    id: "kraeuterseitlinge",
    name: "Kräuterseitlinge",
    jp: "エリンギ",
    desc: "Grilled king oyster mushrooms.",
    price: 4.5,
    category: "grill",
    img: "/images/mushroom.jpg",
    veg: true,
  },

  // ── Set Menüs ─────────────────────────────────────────────
  {
    id: "veggie-menu",
    name: "Veggie-Menü",
    jp: "野菜セット",
    desc: "Zucchini, cherry tomato, water chestnut, shiitake & okra skewers.",
    price: 8.9,
    category: "sets",
    img: "/images/veg.jpg",
    veg: true,
  },
  {
    id: "chicken-menu",
    name: "Chicken-Menü",
    jp: "チキンセット",
    desc: "Yakitori, tebasaki, chicken meatballs & chicken hawaii.",
    price: 9.9,
    category: "sets",
    img: "/images/tori.jpg",
    popular: true,
  },
  {
    id: "seafood-menu",
    name: "Seafood-Menü",
    jp: "海鮮セット",
    desc: "Redfish fillet, salmon, squid & king prawns.",
    price: 11.9,
    category: "sets",
    img: "/images/fish.jpg",
    popular: true,
  },
  {
    id: "mixed-menu",
    name: "Mixed Meat-Menü",
    jp: "ミックスセット",
    desc: "Yakitori, pork, cheese-stuffed beef, lamb & duck breast.",
    price: 13.5,
    category: "sets",
    img: "/images/beef.jpg",
    popular: true,
  },

  // ── Vorspeisen (Starters) ─────────────────────────────────
  {
    id: "edamame",
    name: "Edamame",
    jp: "枝豆",
    desc: "Steamed soybeans, flaky sea salt.",
    price: 4.5,
    category: "starters",
    img: "/images/edamame.jpg",
    veg: true,
  },
  {
    id: "wakame",
    name: "Wakame Salat",
    jp: "わかめ",
    desc: "Seaweed salad, sesame dressing.",
    price: 4.5,
    category: "starters",
    img: "/images/salad.jpg",
    veg: true,
  },
  {
    id: "kimchi",
    name: "Kimchi",
    jp: "キムチ",
    desc: "Spicy fermented cabbage.",
    price: 4.5,
    category: "starters",
    img: "/images/nasu.jpg",
    veg: true,
  },
  {
    id: "kkakdugi",
    name: "Kkakdugi",
    jp: "カクテキ",
    desc: "Spicy pickled radish cubes.",
    price: 4.5,
    category: "starters",
    img: "/images/nasu.jpg",
    veg: true,
  },
  {
    id: "miso-soup",
    name: "Miso Suppe",
    jp: "味噌汁",
    desc: "Miso broth, tofu & wakame.",
    price: 3.5,
    category: "starters",
    img: "/images/soup.jpg",
    veg: true,
  },
  {
    id: "chawanmushi",
    name: "Chawanmushi",
    jp: "茶碗蒸し",
    desc: "Steamed savoury egg custard.",
    price: 4.9,
    category: "starters",
    img: "/images/soup.jpg",
  },
  {
    id: "karaage",
    name: "Karaage",
    jp: "唐揚げ",
    desc: "Twice-fried chicken, kewpie mayo, lemon.",
    price: 8.0,
    category: "starters",
    img: "/images/karaage.jpg",
    popular: true,
  },
  {
    id: "crispy-pork",
    name: "Crispy Pork",
    jp: "豚カツ",
    desc: "Crispy fried pork, spicy dip.",
    price: 8.0,
    category: "starters",
    img: "/images/buta.jpg",
  },
  {
    id: "ebi-tempura",
    name: "Ebi Tempura",
    jp: "海老天ぷら",
    desc: "Crispy prawn tempura, tentsuyu dip.",
    price: 7.5,
    category: "starters",
    img: "/images/tempura.jpg",
  },
  {
    id: "veg-tempura",
    name: "Gemüse Tempura",
    jp: "野菜天ぷら",
    desc: "Assorted vegetable tempura.",
    price: 7.0,
    category: "starters",
    img: "/images/tempura.jpg",
    veg: true,
  },

  // ── Salate & Ramen ────────────────────────────────────────
  {
    id: "salat-yakitori",
    name: "Salat mit Yakitori",
    jp: "サラダ焼き鳥",
    desc: "Fresh salad topped with yakitori skewers.",
    price: 8.5,
    category: "ramen",
    img: "/images/salad.jpg",
  },
  {
    id: "salat-lachs",
    name: "Salat mit Lachs",
    jp: "サラダ鮭",
    desc: "Fresh salad with grilled salmon.",
    price: 9.9,
    category: "ramen",
    img: "/images/salad.jpg",
  },
  {
    id: "salat-rinderfilet",
    name: "Salat mit Rinderfilet",
    jp: "サラダ牛",
    desc: "Fresh salad with grilled beef fillet.",
    price: 9.9,
    category: "ramen",
    img: "/images/salad.jpg",
  },
  {
    id: "kyo-ramen",
    name: "KYO Ramen",
    jp: "KYO ラーメン",
    desc: "Signature ramen — chashu, egg, pak choi.",
    price: 12.5,
    category: "ramen",
    img: "/images/ramen.jpg",
    popular: true,
  },
  {
    id: "beef-ramen",
    name: "Beef Ramen",
    jp: "ビーフラーメン",
    desc: "Rich beef broth, chashu, egg, pak choi.",
    price: 14.5,
    category: "ramen",
    img: "/images/ramen.jpg",
  },
  {
    id: "veggie-ramen",
    name: "Veggie Ramen",
    jp: "ベジラーメン",
    desc: "Vegetable broth, tofu, egg, pak choi.",
    price: 12.5,
    category: "ramen",
    img: "/images/ramen.jpg",
    veg: true,
  },

  // ── Getränke (Drinks) ─────────────────────────────────────
  {
    id: "asahi",
    name: "Asahi (0,33L)",
    jp: "アサヒ",
    desc: "Crisp Japanese lager.",
    price: 4.5,
    category: "drinks",
    img: "/images/beer.jpg",
  },
  {
    id: "kirin",
    name: "Kirin (0,33L)",
    jp: "キリン",
    desc: "Japanese lager.",
    price: 4.5,
    category: "drinks",
    img: "/images/beer.jpg",
  },
  {
    id: "sapporo",
    name: "Sapporo (0,33L)",
    jp: "サッポロ",
    desc: "Japanese lager.",
    price: 4.5,
    category: "drinks",
    img: "/images/beer.jpg",
  },
  {
    id: "berliner-pilsner",
    name: "Berliner Pilsner (0,33L)",
    jp: "ピルスナー",
    desc: "Local Berlin pilsner.",
    price: 4.0,
    category: "drinks",
    img: "/images/beer.jpg",
  },
  {
    id: "sake",
    name: "Sake (160ml)",
    jp: "日本酒",
    desc: "Chilled junmai sake.",
    price: 4.5,
    category: "drinks",
    img: "/images/sake.jpg",
    popular: true,
  },
  {
    id: "chuhai",
    name: "Chuhai",
    jp: "チューハイ",
    desc: "Shochu liqueur, soda water, lemon.",
    price: 8.0,
    category: "drinks",
    img: "/images/highball.jpg",
  },
  {
    id: "tokyo-mule",
    name: "Tokyo Mule",
    jp: "トーキョーミュール",
    desc: "Vodka, ginger beer, lime.",
    price: 8.0,
    category: "drinks",
    img: "/images/highball.jpg",
  },
  {
    id: "coca-cola",
    name: "Coca Cola (0,2L)",
    jp: "コーラ",
    desc: "Ice cold cola.",
    price: 2.8,
    category: "drinks",
    img: "/images/beer.jpg",
  },
  {
    id: "ginger-beer",
    name: "Ginger Beer (0,2L)",
    jp: "ジンジャービア",
    desc: "Spicy ginger beer.",
    price: 3.0,
    category: "drinks",
    img: "/images/beer.jpg",
  },
  {
    id: "ice-tea",
    name: "Homemade Ice Tea (0,3L)",
    jp: "アイスティー",
    desc: "House-brewed iced tea.",
    price: 4.5,
    category: "drinks",
    img: "/images/matcha.jpg",
  },
  {
    id: "haku-vodka",
    name: "Haku Vodka (2cl)",
    jp: "ハクウォッカ",
    desc: "Japanese rice vodka.",
    price: 3.5,
    category: "drinks",
    img: "/images/highball.jpg",
  },
  {
    id: "roku-gin",
    name: "Roku Gin (2cl)",
    jp: "六金",
    desc: "Japanese craft gin.",
    price: 3.5,
    category: "drinks",
    img: "/images/highball.jpg",
  },
  {
    id: "toki-whisky",
    name: "Toki Whisky (2cl)",
    jp: "トキ",
    desc: "Suntory blended whisky.",
    price: 4.0,
    category: "drinks",
    img: "/images/highball.jpg",
  },
  {
    id: "shochu",
    name: "Shochu „Towari“",
    jp: "焼酎",
    desc: "Buckwheat shochu.",
    price: 11.0,
    category: "drinks",
    img: "/images/sake.jpg",
  },
  {
    id: "rotwein",
    name: "Rioja „Altos de Raiza“ (0,2L)",
    jp: "赤ワイン",
    desc: "Spanish red wine, glass.",
    price: 5.5,
    category: "drinks",
    img: "/images/wine.jpg",
  },
  {
    id: "rose",
    name: "Nebla Rosé Verdejo (0,2L)",
    jp: "ロゼ",
    desc: "Spanish rosé, glass.",
    price: 5.5,
    category: "drinks",
    img: "/images/wine.jpg",
  },
  {
    id: "weisswein",
    name: "Nebla Blanco (0,2L)",
    jp: "白ワイン",
    desc: "Spanish white wine, glass.",
    price: 5.0,
    category: "drinks",
    img: "/images/wine.jpg",
  },
  {
    id: "vollrads",
    name: "Schloss Vollrads Riesling",
    jp: "リースリング",
    desc: "Legendary Rheingau riesling, bottle.",
    price: 32.0,
    category: "drinks",
    img: "/images/wine.jpg",
  },
];

export const formatPrice = (p: number) =>
  new Intl.NumberFormat("de-DE", {
    style: "currency",
    currency: "EUR",
  }).format(p);
